<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LIN20002142"><DocLocation><![CDATA[C:\QTP-Hybrid-Framework\QTP-Hybrid-Framework\TestCases\Login]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Login]]></DName>
<Res><![CDATA[Res21]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
ActiveX, Java, Silverlight, WinForms.]]></Details>
<Time><![CDATA[29-08-2023 - 14:45:06]]></Time>
<TimeTick>1693300506</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[login]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[29-08-2023 - 14:45:18]]></Time>
<TimeTick>1693300518</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[29-08-2023 - 14:45:18]]></Time>
<TimeTick>1693300518</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"[&nbsp;Link&nbsp;]"&nbsp;object's&nbsp;parent&nbsp;"[&nbsp;Page&nbsp;]"&nbsp;(class&nbsp;Page).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[29-08-2023 - 14:45:44]]></Time>
<TimeTick>1693300544</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Title = Demo Web Shop<br>Mercury Class = Page<br>]]></Details>
<Time><![CDATA[29-08-2023 - 14:45:44]]></Time>
<TimeTick>1693300544</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="18" status="Warning" nType="Parent description" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="17" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[29-08-2023 - 14:46:05]]></Time>
<TimeTick>1693300565</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Email field is not available]]></Obj>
<Details ><![CDATA[FAILED]]></Details>
<Time><![CDATA[29-08-2023 - 14:46:06]]></Time>
<TimeTick>1693300566</TimeTick>
<NodeArgs eType="User" icon="9" nRep="26" status="Failed" >
<Disp><![CDATA[Email field is not available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[29-08-2023 - 14:46:27]]></Time>
<TimeTick>1693300587</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Password field is not available]]></Obj>
<Details ><![CDATA[FAILED]]></Details>
<Time><![CDATA[29-08-2023 - 14:46:27]]></Time>
<TimeTick>1693300587</TimeTick>
<NodeArgs eType="User" icon="9" nRep="34" status="Failed" >
<Disp><![CDATA[Password field is not available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[29-08-2023 - 14:46:49]]></Time>
<TimeTick>1693300609</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="41" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[Login button is not available]]></Obj>
<Details ><![CDATA[FAILED]]></Details>
<Time><![CDATA[29-08-2023 - 14:46:49]]></Time>
<TimeTick>1693300609</TimeTick>
<NodeArgs eType="User" icon="9" nRep="42" status="Failed" >
<Disp><![CDATA[Login button is not available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"[&nbsp;Link&nbsp;]"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:15]]></Time>
<TimeTick>1693300635</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = Log out<br>Mercury Class = Link<br>]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:15]]></Time>
<TimeTick>1693300635</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="72" status="Warning" nType="Description" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="71" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:18]]></Time>
<TimeTick>1693300638</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="75" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:18]]></Time>
<TimeTick>1693300638</TimeTick>
<NodeArgs eType="User" icon="9" nRep="76" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:22]]></Time>
<TimeTick>1693300642</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="78" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:22]]></Time>
<TimeTick>1693300642</TimeTick>
<NodeArgs eType="User" icon="9" nRep="79" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nandini@Nandini.com"]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:24]]></Time>
<TimeTick>1693300644</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="82" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[Value - 'Nandini@Nandini.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:24]]></Time>
<TimeTick>1693300644</TimeTick>
<NodeArgs eType="User" icon="9" nRep="83" status="Passed" >
<Disp><![CDATA[Value - 'Nandini@Nandini.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:24]]></Time>
<TimeTick>1693300644</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="85" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:24]]></Time>
<TimeTick>1693300644</TimeTick>
<NodeArgs eType="User" icon="9" nRep="86" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nandini@12345"]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:26]]></Time>
<TimeTick>1693300646</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="89" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Value - 'Nandini@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:26]]></Time>
<TimeTick>1693300646</TimeTick>
<NodeArgs eType="User" icon="9" nRep="90" status="Passed" >
<Disp><![CDATA[Value - 'Nandini@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:29]]></Time>
<TimeTick>1693300649</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="92" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:29]]></Time>
<TimeTick>1693300649</TimeTick>
<NodeArgs eType="User" icon="9" nRep="93" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:36]]></Time>
<TimeTick>1693300656</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="96" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:36]]></Time>
<TimeTick>1693300656</TimeTick>
<NodeArgs eType="User" icon="9" nRep="97" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Log out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:43]]></Time>
<TimeTick>1693300663</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="100" >
<Disp><![CDATA[[ Log out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA['[ Log out ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:43]]></Time>
<TimeTick>1693300663</TimeTick>
<NodeArgs eType="User" icon="9" nRep="101" status="Passed" >
<Disp><![CDATA['[ Log out ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:52]]></Time>
<TimeTick>1693300672</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="104" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:52]]></Time>
<TimeTick>1693300672</TimeTick>
<NodeArgs eType="User" icon="9" nRep="105" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:55]]></Time>
<TimeTick>1693300675</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="107" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[29-08-2023 - 14:47:56]]></Time>
<TimeTick>1693300676</TimeTick>
<NodeArgs eType="User" icon="9" nRep="108" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Lavish@Lavish.com"]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:04]]></Time>
<TimeTick>1693300684</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="111" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[Value - 'Lavish@Lavish.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:05]]></Time>
<TimeTick>1693300685</TimeTick>
<NodeArgs eType="User" icon="9" nRep="112" status="Passed" >
<Disp><![CDATA[Value - 'Lavish@Lavish.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:08]]></Time>
<TimeTick>1693300688</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="114" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:08]]></Time>
<TimeTick>1693300688</TimeTick>
<NodeArgs eType="User" icon="9" nRep="115" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Lavish@12345"]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:16]]></Time>
<TimeTick>1693300696</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="118" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[Value - 'Lavish@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:17]]></Time>
<TimeTick>1693300697</TimeTick>
<NodeArgs eType="User" icon="9" nRep="119" status="Passed" >
<Disp><![CDATA[Value - 'Lavish@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:19]]></Time>
<TimeTick>1693300699</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="121" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:19]]></Time>
<TimeTick>1693300699</TimeTick>
<NodeArgs eType="User" icon="9" nRep="122" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:23]]></Time>
<TimeTick>1693300703</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="125" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:23]]></Time>
<TimeTick>1693300703</TimeTick>
<NodeArgs eType="User" icon="9" nRep="126" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ Log out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:26]]></Time>
<TimeTick>1693300706</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="129" >
<Disp><![CDATA[[ Log out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA['[ Log out ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:27]]></Time>
<TimeTick>1693300707</TimeTick>
<NodeArgs eType="User" icon="9" nRep="130" status="Passed" >
<Disp><![CDATA['[ Log out ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Demo Web Shop ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:29]]></Time>
<TimeTick>1693300709</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="132" >
<Disp><![CDATA[[ Demo Web Shop ].Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA['[ Browser ] browser' closed]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[29-08-2023 - 14:48:29]]></Time>
<TimeTick>1693300709</TimeTick>
<NodeArgs eType="User" icon="9" nRep="133" status="Passed" >
<Disp><![CDATA['[ Browser ] browser' closed]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="29-08-2023 - 14:45:14" eTime="29-08-2023 - 14:48:30" passed="18" failed="5" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Failed" >
<Disp><![CDATA[login Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[Login Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="29-08-2023 - 14:45:01" eTime="29-08-2023 - 14:48:30" passed="18" failed="5" warnings="3" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Login Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>